module.exports = (teamName) => {
    switch (teamName) {
        case "Network":
            return "mahdi.ghorbani"
            //return "alireza.tajalli"
        case "User-Interface":
            return "mohamadjavad.rahmani"
        case "Financial":
            return "hossein.yavari"
        case "Monitoring":
            return "reza.mahmoudi"
        case "Hardware":
            return "bagher.salami"
        case "Graphic":
            return "mohammad.mansouri"
        case "Devops":
            return "ali.mousavi"
        case "Digital-Marketing":
            return "mostafa.bolandifar"
        case "Office":
            return "sanam.hosseini"
        case "Artificial-Intelligence":
            return "mohammad.hajizadeh"
        case "Business-Development":
            return "mohsen.bagheri"
        case "Translation":
            return "hassan.rasoulizadeh"
        case "Android":
            return "ali.forghani"
        case "Client":
            return "mohsen.bazghandi"
        case "DotNet":
            return "samin.hajimohammad"
        case "Infrastructure":
            return "nasser.torabzadeh"
        case "Project-Control":
            return "mohammadreza.marjani"
        case "Data-Gathering":
            return "hossein.akbarian"
        case "DataBase":
            return "saeed.shidkalaee"
        case "Wordpress":
            return "jafar.rasoulizadeh"
        case "Security":
            return "alireza.abedini"
        case "Cyject":
            return "mahdi.houshmand"
        case "Tahlilgaran":
            return "jalal.rasoulizadeh"
        case "Technical-Support":
            return "sara.kazemzadeh"
        case "IOS":
            return "mahdi.fekri"
        case "Customer-Support":
            return "shahrbanou.kosar"
        case "API":
            return "mehran.rahbardar"
        case "Health-Club":
            return "iman.shariati"
        case "CUP":
            return "saeed.yousefi"
        default :
            return false
    }
}